import type { Metadata } from 'next'

import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'

import { Ubuntu } from 'next/font/google';

const ubuntu = Ubuntu({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-ubuntu',
  weight: ['300', '400', '500', '700']
});

export const metadata: Metadata = {
  title: 'Motion App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={ubuntu.className}>{children}</body>
    </html>
    </ClerkProvider>
  )
}
